#!/bin/sh 
# 
# Start afp daemon 
# 
start() { 
		echo "Starting metadaemon"
		LD_LIBRARY_PATH=/usr/local/lib /usr/local/sbin/cnid_metad
        echo "Starting afpd"
        LD_LIBRARY_PATH=/usr/local/lib /usr/local/sbin/afpd
} 

stop() { 
        echo "Stopping afpd"
        kill `cat /var/run/afpd`
        echo "Stopping metadaemon"
        kill `cat /var/run/cnid_metad`
} 
restart() { 
        stop 
        start 
} 

case "$1" in 
        start) 
                start 
                ;; 
        stop) 
                stop 
                ;; 
        restart) 
                restart 
                ;; 
        cleanup) 
                ;; 
        *) 
                echo $"Usage: $0 {start|stop|restart}" 
                exit 1 
esac 

exit $?