#!/bin/sh
#
# 
#
# 
# Description
# 
# @license		GNU General Public License
# @author		Thomas Brandstetter
# @link			http://www.pulsaros.com
# @email		admin@pulsaros.com
# 
# @file			config
# @version		0.7alpha
# @date			07/04/2011
# 
# Copyright (c) 2009-2011
#
# ##############################################
 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT
# HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR
# FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE
# OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
# COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.COPYRIGHT HOLDERS WILL NOT
# BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://gnu.org/licenses/>.
# 

#
# Replay config to PulsarOS.
#

#
# Variables
#
# ============================================================
CONFIG_HOME=/pulsarroot/configs

# Make sure all requirements exists
[ -d /etc ] || exit 0

echo -n "Replay config to PulsarOS: "

[ -f $CONFIG_HOME/system/fstab ] && cp -p $CONFIG_HOME/system/fstab /etc/fstab
[ -f $CONFIG_HOME/nfs/exports ] && cp -p $CONFIG_HOME/nfs/exports /etc/exports
[ -f $CONFIG_HOME/system/passwd ] && cp -p $CONFIG_HOME/system/passwd /etc/passwd
[ -f $CONFIG_HOME/system/group ] && cp -p $CONFIG_HOME/system/group /etc/group
[ -f $CONFIG_HOME/system/shadow ] && cp -p $CONFIG_HOME/system/shadow /etc/shadow
[ -f $CONFIG_HOME/system/TZ ] && cp -p $CONFIG_HOME/system/TZ /etc/TZ
[ -f $CONFIG_HOME/network/resolv.conf ] && cp -p $CONFIG_HOME/network/resolv.conf /etc/resolv.conf
[ -f $CONFIG_HOME/network/defaultrouter ] && cp -p $CONFIG_HOME/network/resolv.conf /etc/defaultrouter

echo "OK"

exit $?