#!/bin/sh
#
#
#
#
# Description
#
# @license		GNU General Public License
# @author		Thomas Brandstetter
# @link			http://www.pulsaros.com
# @email		admin@pulsaros.com
# 
# @file			ntp
# @version		0.7alpha
# @date			07/04/2011
# 
# Copyright (c) 2009-2011
#
# ##############################################

#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT
# HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR
# FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE
# OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
# COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.COPYRIGHT HOLDERS WILL NOT
# BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://gnu.org/licenses/>.
#

#
# Startup ntp daemon
#

#
# Variables
#
# ============================================================
POOL=`cat /pulsarroot/configs/system/ntpd.conf`
DAEMON=/usr/sbin/ntpd

case "$1" in
	start)
		if [ -x $DAEMON ]; then
			echo -n "Starting ntpd"
			$DAEMON -p $POOL
			if [ `echo $?` == 0 ]; then
				PID=`ps|grep ntpd|grep -v grep |awk '{print $1}'`
				echo $PID > /var/run/ntpd.pid
			fi
		fi
	;;
	stop) echo -n "Stopping $DESC: $NAME"
		if [ -f /var/run/ntpd.pid ]; then
			kill -9 `cat /var/run/ntpd.pid`
		fi
	;;
	reload|force-reload) echo -n "Reload ntp configuration"
		kill -HUP `cat /var/run/ntpd.pid`
	;;
	restart) echo "Restarting $ntp"
		$0 stop
		sleep 1
		$0 start
	;;
	*) echo "Usage: ntp {start|stop|restart|reload|force-reload}" >&2
		exit 1
		;;
esac

exit 0
