#!/bin/sh
#
# 
#
# 
# Description
# 
# @license		GNU General Public License
# @author		Thomas Brandstetter
# @link			http://www.pulsaros.com
# @email		admin@pulsaros.com
# 
# Copyright (c) 2009-2012
#
# ##############################################
 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT
# HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR
# FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE
# OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
# COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.COPYRIGHT HOLDERS WILL NOT
# BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://gnu.org/licenses/>.
#

#
# Power save daemon
#

#
# Variables
#
# ============================================================
log=/var/log/power.log
POWER_CONFIG="/pulsarroot/configs/system/power.conf"
POWER_HOSTS="/pulsarroot/configs/system/power_hosts.conf"

while :;do
	power=0
	mode=`cat  $POWER_CONFIG | awk '{ print $1 }'`
	timeout=`cat $POWER_CONFIG | awk '{ print $2 }'`
	if [ $timeout != "0" ]; then
		sleep $timeout
		for i in `cat $POWER_HOSTS`; do
			#if hosts are available do nothing
			if ping -c3 ${i}; then
				power=`expr $power + 1`
			fi
		done
		if [ $power = 0 ]; then
			echo "Suspend to Ram ..." >> $log
			echo " " >> $log
			case $mode in
				'poweroff')
					poweroff
					;;
				'standby')
					echo -n standby > /sys/pm/state
					;;
				*)
					echo "wrong mode" >> $log
					;;
			esac
		fi
	else
		sleep 120
	fi
done