#!/bin/sh
#
# 
#
# 
# Description
# 
# @license		GNU General Public License
# @author		Thomas Brandstetter
# @link			http://www.pulsaros.com
# @email		admin@pulsaros.com
# 
# @file			power
# @version		0.7alpha
# @date			07/04/2011
# 
# Copyright (c) 2009-2011
#
# ##############################################
 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT
# HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR
# FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE
# OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
# COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.COPYRIGHT HOLDERS WILL NOT
# BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://gnu.org/licenses/>.
#

#
# Power save daemon
#

#
# Variables
#
# ============================================================
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
log=/var/log/power.log

while :;do
	mode=`cat /pulsarroot/configs/system/power.conf | awk '{ print $1 }'`
	timeout=`cat /pulsarroot/configs/system/power.conf | awk '{ print $2 }'`
	if [ $timeout != "0" ]; then
		sleep $timeout
		smbstatus=`/usr/local/bin/smbstatus --processes|tail +5|wc -l`
		sshfsstatus=`netstat -an|grep ":22"|grep -c ESTABLISHED`
		if [ $smbstatus == "0" ] && [ $sshfsstatus == "0" ]; then
			echo "Suspend to Ram ..." >> $log
			echo " " >> $log
			case $mode in
				'poweroff')
					poweroff
					;;
				'standby')
					echo -n standby > /sys/pm/state
					;;
				*)
					echo "wrong mode" >> $log
					;;
			esac
		fi
	else
		sleep 120
	fi
done
