#!/bin/sh
#
# 
#
# 
# Description
# 
# @license		GNU General Public License
# @author		Thomas Brandstetter
# @link			http://www.pulsaros.com
# @email		admin@pulsaros.com
# 
# Copyright (c) 2009-2012
#
# ##############################################
 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT
# HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR
# FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE
# OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
# COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.COPYRIGHT HOLDERS WILL NOT
# BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://gnu.org/licenses/>.
#

#
# Adjust Harddisk spindown settings
#

#
# Variables
#
# ============================================================
SPINDOWN_CONFIG=/pulsarroot/configs/system/spindown.conf

if [ -f $SPINDOWN_CONFIG ]; then
	CONFIG=`cat $SPINDOWN_CONFIG`
	for i in `cat /proc/mdstat |grep active| awk '{ print $1}'`; do
		for x in `mdadm --detail /dev/$i|grep dev|grep -v md0|awk '{ print $7 }'`; do
			logger "Setting harddisk spindown to $CONFIG on disk $x"
			hdparm -S $CONFIG $x
		done
	done
fi